### PR TITLE
Complete refurbishment of the documentation

### PR DESCRIPTION
**Pull request by fwitte**
Hi everyone,

I pushed the structure idea with the new template to this branch. You can have a look at the documentation here: https://tespy--355.org.readthedocs.build/en/355/contents.html

I'd love to get some feedback and suggestions on

- the outline/structure
  - Are the headlines clear to understand?
  - Are you missing stuff?
  - Is there too much stuff?
- the template
  - Are there elements and/or styles you'd like to change?
  - Are features missing?
- the landing page
  - (not yet ready, but once it is): Do you find it appealing?

Looking forward to a fruitful discussion!

If you want to make changes yourselves, you are free to do so! There are two possible ways:

- Directly push to this branch
- Create a fork of the repo/update your fork to fetch the current state of this branch, make the changes there and open a pull request.

In any case, if you want to make changes, please reach out to me, if you have questions or trouble making and testing them. To create the documentation on your local machine for testing it before pushing the changes, you need to install tespy with the .[dev] flag:

```
conda activate your_tespy_environment
cd /paht/to/clone/of/tespy
pip install -e .[dev]
```
Then make the changes and render the documentation with

```
python -m sphinx ./docs/ ./docs/_build
```

A `_build` folder will appear in the `docs` folder, where you can open the contents.html page.

Thank you so much for your help :)

### CODE REVIEW

**Comment by fwitte** [comment]
@ChaofanChen @nkawerau @andreas-sm @fgasa @maltefritz 

I also added you to the oemof-tespy team, which allows you to directly push to or review this pull request by directly commenting on the code changes, if you like.

**Comment by NicholasFry** [comment]
Looking good! I only took a hard look at the Installation and setup/Modeling basic systems, so far.

**•	the outline/structure**
_o	Are the headlines clear to _understand?__
I think so. Capital Case on Installation and setup

_o	Are you missing stuff?_
1.	First steps: broken link to image 1; api/_images/intro_district_heating_scheme.svg
2.	Start your calculation: broken link to image; api/_images/tutorial_heat_pump.svg

I will add more later.

**Comment by fwitte** [comment]
Thanks to both of you!

>     * The introduction page of "Modeling Basic Systems" is very attractive and has a modern touch. It would be awesome if "Advanced Tutorial" and "Real World Applications" will have the same feature. In my opinon this function is not necessary in "TESPy modules". It seems to be a little bit overpowered.

Well it is started now, can be changed back at any time.

>     * In "API documentation" "tespy.components.module" are a lot content. It would be nice if it will be structured it as you do  in "Component" in "TESPy modules".

You mean with the list at the beginning?

>     * Maybe you can add an example for creating a automatic model documentation in LATEX. The appropriate place would be in "Advanced tutorial" or in "Advanced Features".

Good idea, but it would not be on my priority list actually.

>     * The headline "Real World Applications" sounds unreachable. Maybe you can name it "Applications", "Examples" or something like this.

Renamed to "Example Applications"

>     * Finally, just a small note: The next "Online Stammtisch" will not take place in June. It will take place on September 19.

Will be 26th most likely, at least I do not have time on the 19th.

> I hope my comments will help a little bit. Beste regards

Definitively, thank you!

---

>     1. First steps: broken link to image 1; api/_images/intro_district_heating_scheme.svg
>        image
> 
>     2. Start your calculation: broken link to image; api/_images/tutorial_heat_pump.svg
>        image

Those will be fixed step by step once the respective section is finished.

**Comment by ChaofanChen** [comment]
Hi @fwitte,

thank you very much for the nice work on the refurbishment of the online document. 

Only one comment from my side, it would be better to have a small section to present the highlight publication list or the projects using TESPy just like what [OGS](https://www.opengeosys.org/publications/) and [Coolprop](http://www.coolprop.org/index.html#projects-using-coolprop) did.

Best regards,
Chaofan

**Comment by fwitte** [comment]
@NicholasFry, @maltefritz, @ChaofanChen, @fgasa, @jfreissmann: Thank you for your feedback, rework is nearly done. I will present the new documentation on Monday, if anybody is interested (user meeting rescheduled from last Monday at 17:00 CEST).

Have a nice weekend, best!

**Pull request merged**
